language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# before_deploy:
#   - mkdir -p before-deploy/
#   # - cp scripts/*.sh before-deploy/
#   # - cp appspec.yml before-deploy/
#   - cp build/libs/*.jar before-deploy/
#   - cd before-deploy && zip -r before-deploy *
#   - cd ../ && mkdir -p deploy
#   - mv before-deploy/before-deploy.zip deploy/do-it-quant.zip